# Generated by Django 3.2.6 on 2021-10-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='Awesome Assignment!', max_length=300),
        ),
    ]
