# Generated by Django 3.2.6 on 2021-11-06 06:56

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=assignments.models.upload_local),
        ),
        migrations.AlterField(
            model_name='submission',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=assignments.models.upload_local),
        ),
    ]
