# Generated by Django 3.2.6 on 2021-11-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_auto_20211123_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.FloatField(default=-1),
        ),
    ]
