# Generated by Django 3.2.6 on 2021-11-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_releasedate'),
        ('assignments', '0008_alter_submission_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='_assignments_submission_comments_+', to='posts.Comment'),
        ),
    ]
