# Generated by Django 3.2.6 on 2021-11-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_alter_submission_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
