# Generated by Django 3.2.6 on 2021-11-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_assignment_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
