# Generated by Django 3.2.6 on 2021-11-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_wizardcard_wizard'),
        ('assignments', '0012_alter_submission_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='author',
            field=models.ManyToManyField(default='self.course.instructors.all()[0]', related_name='_assignments_assignment_author_+', to='courses.UserProfile'),
        ),
    ]
