# Generated by Django 3.2.6 on 2021-09-30 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(default='Learning', max_length=100)),
                ('courseID', models.CharField(default='LR101y2000s1', max_length=15)),
                ('courseCode', models.CharField(default='LR101', max_length=7)),
                ('instructors', models.ManyToManyField(related_name='_courses_course_instructors_+', to='courses.UserProfile')),
                ('students', models.ManyToManyField(related_name='_courses_course_students_+', to='courses.UserProfile')),
            ],
        ),
    ]
