# Generated by Django 3.2.6 on 2021-11-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WizardCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=3)),
                ('wizard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='wizardcards',
            field=models.ManyToManyField(related_name='_courses_course_wizardcards_+', to='courses.WizardCard'),
        ),
    ]
