# Generated by Django 3.2.6 on 2021-11-26 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20211109_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizardcard',
            name='wizard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.userprofile'),
        ),
    ]
