# Generated by Django 3.2.6 on 2021-11-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_otptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='timeout',
            field=models.IntegerField(default=120),
        ),
    ]
