# Generated by Django 3.2.6 on 2021-11-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211121_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datepublished',
            new_name='datemade',
        ),
    ]
