# Generated by Django 3.2.6 on 2021-11-22 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20211109_1952'),
        ('assignments', '0005_auto_20211106_1226'),
        ('posts', '0007_auto_20211122_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('task', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.userprofile')),
            ],
        ),
    ]
