# Generated by Django 3.2.6 on 2021-11-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='_posts_post_comments_+', to='posts.Comment'),
        ),
    ]
