# Generated by Django 3.2.6 on 2021-11-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_wizardcard_wizard'),
        ('posts', '0012_alter_post_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ManyToManyField(related_name='_posts_post_author_+', to='courses.UserProfile'),
        ),
    ]
